# Generated by Django 5.2.11 on 2026-02-04 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('EX', 'Estrangeiro')], default='PF', max_length=2, verbose_name='tipo de pessoa')),
                ('cpf_cnpj', models.CharField(help_text='Documento com máscara', max_length=18, verbose_name='CPF/CNPJ')),
                ('cpf_cnpj_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='hash do documento')),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social / nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, verbose_name='inscrição municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, verbose_name='inscrição estadual')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('codigo_ibge', models.CharField(blank=True, max_length=7, verbose_name='código IBGE')),
                ('consentimento_lgpd', models.BooleanField(default=False, help_text='Cliente autorizou o uso dos dados', verbose_name='consentimento LGPD')),
                ('data_consentimento', models.DateTimeField(blank=True, null=True, verbose_name='data do consentimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['razao_social'],
            },
        ),
    ]
