# Generated by Django 6.0.1 on 2026-02-09 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('core', '0006_conexaoexterna_rotinas_alter_conexaoexterna_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_cliente_documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cadastro_completo',
            field=models.BooleanField(default=True, help_text='Indica se o cliente tem todos os dados preenchidos (CPF, endereço, etc.)', verbose_name='cadastro completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', help_text='Documento com máscara', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj_hash',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, verbose_name='hash do documento'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_cnpj_hash__gt', '')), fields=('tenant', 'cpf_cnpj_hash'), name='unique_cliente_documento'),
        ),
    ]
