# Generated by Django 5.2.11 on 2026-02-04 19:34

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_lancamento', models.DateField(db_index=True, verbose_name='data lançamento')),
                ('data_competencia', models.DateField(db_index=True, verbose_name='competência')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='nº documento')),
                ('historico', models.TextField(verbose_name='histórico')),
                ('origem_tipo', models.CharField(blank=True, help_text='movimento_caixa, nota_fiscal, ajuste', max_length=50, verbose_name='tipo origem')),
                ('origem_id', models.CharField(blank=True, max_length=36, verbose_name='ID origem')),
                ('estornado', models.BooleanField(default=False, verbose_name='estornado')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor total')),
            ],
            options={
                'verbose_name': 'lançamento contábil',
                'verbose_name_plural': 'lançamentos contábeis',
                'ordering': ['-data_lancamento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartidaLancamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('historico_complementar', models.CharField(blank=True, max_length=200, verbose_name='complemento')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(db_index=True, max_length=20, verbose_name='código')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('RESULTADO', 'Resultado')], max_length=20, verbose_name='tipo')),
                ('natureza', models.CharField(choices=[('D', 'Devedora'), ('C', 'Credora')], max_length=1, verbose_name='natureza')),
                ('nivel', models.PositiveSmallIntegerField(default=1, verbose_name='nível')),
                ('permite_lancamento', models.BooleanField(default=True, verbose_name='permite lançamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'plano de contas',
                'verbose_name_plural': 'planos de contas',
                'ordering': ['codigo'],
            },
        ),
    ]
