# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='lancamento_estorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estorno_de', to='contabil.lancamentocontabil'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='partidalancamento',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='contabil.centrocusto'),
        ),
        migrations.AddField(
            model_name='partidalancamento',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabil.lancamentocontabil'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontas', to='contabil.planocontas'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='partidalancamento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabil.planocontas'),
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('tenant', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='planocontas',
            unique_together={('tenant', 'codigo')},
        ),
    ]
