# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroFiscalServicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('competencia', models.DateField(db_index=True, verbose_name='competência')),
                ('municipio_ibge', models.CharField(max_length=7, verbose_name='município IBGE')),
                ('total_notas', models.PositiveIntegerField(default=0, verbose_name='total notas')),
                ('valor_servicos', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor serviços')),
                ('valor_iss', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor ISS')),
                ('valor_iss_retido', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='ISS retido')),
                ('fechado', models.BooleanField(default=False, verbose_name='fechado')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='data fechamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'livro fiscal de serviços',
                'verbose_name_plural': 'livros fiscais de serviços',
                'ordering': ['-competencia'],
                'unique_together': {('tenant', 'competencia', 'municipio_ibge')},
            },
        ),
    ]
