# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data/hora abertura')),
                ('saldo_abertura', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='saldo na abertura')),
                ('fundo_troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='fundo de troco')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('hash_registro', models.CharField(editable=False, max_length=64, verbose_name='hash do registro')),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64, verbose_name='hash anterior')),
                ('fechado', models.BooleanField(default=False, verbose_name='fechado')),
            ],
            options={
                'verbose_name': 'abertura de caixa',
                'verbose_name_plural': 'aberturas de caixa',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('identificador', models.CharField(help_text='Ex: CAIXA-01, PDV-LOJA', max_length=50, verbose_name='identificador')),
                ('tipo', models.CharField(choices=[('FISICO', 'Caixa Físico'), ('VIRTUAL', 'Caixa Virtual')], default='FISICO', max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('FECHADO', 'Fechado'), ('ABERTO', 'Aberto'), ('BLOQUEADO', 'Bloqueado')], default='FECHADO', max_length=20, verbose_name='status')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='saldo atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'caixa',
                'verbose_name_plural': 'caixas',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data/hora fechamento')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, help_text='Saldo calculado pelo sistema', max_digits=14, verbose_name='saldo sistema')),
                ('saldo_informado', models.DecimalField(decimal_places=2, help_text='Saldo informado pelo operador', max_digits=14, verbose_name='saldo informado')),
                ('diferenca', models.DecimalField(decimal_places=2, help_text='Diferença entre sistema e informado', max_digits=14, verbose_name='diferença')),
                ('detalhamento', models.JSONField(default=dict, help_text='Totais por forma de pagamento', verbose_name='detalhamento')),
                ('justificativa_diferenca', models.TextField(blank=True, verbose_name='justificativa da diferença')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='data aprovação')),
                ('observacao_aprovador', models.TextField(blank=True, verbose_name='observação do aprovador')),
                ('hash_registro', models.CharField(editable=False, max_length=64, verbose_name='hash do registro')),
            ],
            options={
                'verbose_name': 'fechamento de caixa',
                'verbose_name_plural': 'fechamentos de caixa',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('SANGRIA', 'Sangria'), ('SUPRIMENTO', 'Suprimento'), ('ESTORNO', 'Estorno')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('hash_registro', models.CharField(editable=False, max_length=64, verbose_name='hash do registro')),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64, verbose_name='hash anterior')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data/hora')),
            ],
            options={
                'verbose_name': 'movimento de caixa',
                'verbose_name_plural': 'movimentos de caixa',
                'ordering': ['-data_hora'],
            },
        ),
    ]
