# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('nfse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturacaixa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aberturas_caixa', to=settings.AUTH_USER_MODEL, verbose_name='operador'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='operador_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_operando', to=settings.AUTH_USER_MODEL, verbose_name='operador atual'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aberturas', to='caixa.caixa', verbose_name='caixa'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='abertura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fechamento', to='caixa.aberturacaixa', verbose_name='abertura'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='aprovador'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_caixa', to=settings.AUTH_USER_MODEL, verbose_name='operador'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='caixa.aberturacaixa', verbose_name='abertura'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.formapagamento', verbose_name='forma de pagamento'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='movimento_estornado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estorno', to='caixa.movimentocaixa', verbose_name='movimento estornado'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='nfse.notafiscalservico', verbose_name='nota fiscal'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='caixa',
            unique_together={('tenant', 'identificador')},
        ),
    ]
