# Generated by Django 5.2.11 on 2026-02-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações gerais do operador', verbose_name='observação'),
        ),
    ]
