# Generated by Django 5.2.11 on 2026-02-09 12:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_fechamentocaixa_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='emolumento',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='emolumento'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='estado',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ESTADO'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fecad',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FECAD'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='femal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEMAL'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fepadsaj',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEPADSAJ'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fesemps',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FESEMPS'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='funcomp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNCOMP'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fundaf',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDAF'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fundepeg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDEPEG'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fundesp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDESP'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='funemp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNEMP'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='funesp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNESP'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='funproge',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNPROGE'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='iss',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ISS'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='protocolo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='protocolo'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='status_item',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='status do item'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='taxa_judiciaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='taxa judiciária'),
        ),
    ]
