# Generated by Django 5.2.11 on 2026-02-09 13:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_import_movements'),
        ('caixa', '0004_movimentocaixa_campos_cartorarios'),
        ('core', '0006_conexaoexterna_rotinas_alter_conexaoexterna_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoImportado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('confirmado', models.BooleanField(default=False, verbose_name='confirmado')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('protocolo', models.CharField(blank=True, default='', max_length=100, verbose_name='protocolo')),
                ('status_item', models.CharField(blank=True, default='', max_length=100, verbose_name='status do item')),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='nome do apresentante')),
                ('iss', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ISS')),
                ('fundesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDESP')),
                ('funesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNESP')),
                ('estado', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estado')),
                ('fesemps', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FESEMPS')),
                ('funemp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNEMP')),
                ('funcomp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNCOMP')),
                ('fepadsaj', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEPADSAJ')),
                ('funproge', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNPROGE')),
                ('fundepeg', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDEPEG')),
                ('fundaf', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDAF')),
                ('femal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEMAL')),
                ('fecad', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FECAD')),
                ('emolumento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='emolumento')),
                ('taxa_judiciaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='taxa judiciária')),
                ('abertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importados', to='caixa.aberturacaixa', verbose_name='abertura')),
                ('conexao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importados', to='core.conexaoexterna', verbose_name='conexão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
                ('movimento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacao_origem', to='caixa.movimentocaixa', verbose_name='movimento destino')),
                ('rotina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importados', to='backoffice.rotina', verbose_name='rotina')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'movimento importado',
                'verbose_name_plural': 'movimentos importados',
                'ordering': ['-importado_em'],
            },
        ),
    ]
