# Generated by Django 6.0.1 on 2026-02-10 14:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_import_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='valor_receita_adicional_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 1'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='valor_receita_adicional_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 2'),
        ),
        migrations.AddField(
            model_name='movimentoimportado',
            name='valor_receita_adicional_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 1'),
        ),
        migrations.AddField(
            model_name='movimentoimportado',
            name='valor_receita_adicional_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 2'),
        ),
    ]
