# Generated by Django 5.2.11 on 2026-02-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_add_receita_adicional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoimportado',
            name='data_ato',
            field=models.DateField(blank=True, help_text='Data da confecção do ato (importada da SQL)', null=True, verbose_name='data do ato'),
        ),
    ]
