# Generated by Django 5.2.11 on 2026-02-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_add_data_ato'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='data_ato',
            field=models.DateField(blank=True, help_text='Data da confecção do ato (importada da SQL)', null=True, verbose_name='data do ato'),
        ),
    ]
