# Generated by Django 6.0.1 on 2026-02-11 14:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_add_data_ato_movimentocaixa'),
        ('core', '0007_add_chave_servico_andamento_ri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAtoImportado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor')),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantidade')),
                ('data_ato', models.DateField(blank=True, null=True, verbose_name='data do ato')),
                ('status_item', models.CharField(blank=True, default='', max_length=100, verbose_name='status do item')),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='nome do apresentante')),
                ('iss', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ISS')),
                ('fundesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDESP')),
                ('funesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNESP')),
                ('estado', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estado')),
                ('fesemps', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FESEMPS')),
                ('funemp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNEMP')),
                ('funcomp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNCOMP')),
                ('fepadsaj', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEPADSAJ')),
                ('funproge', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNPROGE')),
                ('fundepeg', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDEPEG')),
                ('fundaf', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDAF')),
                ('femal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEMAL')),
                ('fecad', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FECAD')),
                ('emolumento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='emolumento')),
                ('taxa_judiciaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='taxa judiciária')),
                ('valor_receita_adicional_1', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 1')),
                ('valor_receita_adicional_2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('movimento_importado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='caixa.movimentoimportado', verbose_name='movimento importado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'item de ato importado',
                'verbose_name_plural': 'itens de atos importados',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemAtoMovimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor')),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantidade')),
                ('data_ato', models.DateField(blank=True, null=True, verbose_name='data do ato')),
                ('status_item', models.CharField(blank=True, default='', max_length=100, verbose_name='status do item')),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='nome do apresentante')),
                ('iss', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ISS')),
                ('fundesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDESP')),
                ('funesp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNESP')),
                ('estado', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estado')),
                ('fesemps', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FESEMPS')),
                ('funemp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNEMP')),
                ('funcomp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNCOMP')),
                ('fepadsaj', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEPADSAJ')),
                ('funproge', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNPROGE')),
                ('fundepeg', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDEPEG')),
                ('fundaf', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FUNDAF')),
                ('femal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FEMAL')),
                ('fecad', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='FECAD')),
                ('emolumento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='emolumento')),
                ('taxa_judiciaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='taxa judiciária')),
                ('valor_receita_adicional_1', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 1')),
                ('valor_receita_adicional_2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Adicional 2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='caixa.movimentocaixa', verbose_name='movimento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'item de ato do movimento',
                'verbose_name_plural': 'itens de atos do movimento',
                'ordering': ['created_at'],
            },
        ),
    ]
