# Generated by Django 5.2.11 on 2026-02-12 20:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_item_ato_master_detail'),
        ('core', '0007_add_chave_servico_andamento_ri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoimportado',
            name='prazo_quitacao',
            field=models.DateField(blank=True, help_text='Data limite para quitação total do protocolo', null=True, verbose_name='prazo de quitação'),
        ),
        migrations.AddField(
            model_name='movimentoimportado',
            name='status_recebimento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('QUITADO', 'Quitado'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20, verbose_name='status de recebimento'),
        ),
        migrations.CreateModel(
            name='ParcelaRecebimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor da parcela')),
                ('numero_parcela', models.PositiveIntegerField(default=1, verbose_name='número da parcela')),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recebido em')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_recebidas', to='caixa.aberturacaixa', verbose_name='abertura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_recebimento', to='core.formapagamento', verbose_name='forma de pagamento')),
                ('movimento_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcela_recebimento', to='caixa.movimentocaixa', verbose_name='movimento de caixa')),
                ('movimento_importado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='caixa.movimentoimportado', verbose_name='movimento importado')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='recebido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'parcela de recebimento',
                'verbose_name_plural': 'parcelas de recebimento',
                'ordering': ['numero_parcela'],
            },
        ),
    ]
