# Generated by Django 6.0.1 on 2026-02-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_data_confirmados_quitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturacaixa',
            name='saldo_editado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última edição', null=True, verbose_name='editado em'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='saldo_editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aberturas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='editado por'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='saldo_inicial_editado',
            field=models.BooleanField(default=False, help_text='Se True, já foi editado hoje e não pode ser alterado novamente', verbose_name='saldo inicial editado'),
        ),
        migrations.AddField(
            model_name='aberturacaixa',
            name='saldo_inicial_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor original antes da edição (para auditoria)', max_digits=14, null=True, verbose_name='saldo inicial original'),
        ),
    ]
