# Generated by Django 6.0.1 on 2026-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_add_saldo_edit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='cliente_nome',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nome do apresentante'),
        ),
    ]
