# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, verbose_name='inscrição municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, verbose_name='inscrição estadual')),
                ('regime_tributario', models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real'), ('MEI', 'Microempreendedor Individual')], default='SIMPLES', max_length=20, verbose_name='regime tributário')),
                ('logradouro', models.CharField(max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('codigo_ibge', models.CharField(help_text='Código IBGE do município', max_length=7, verbose_name='código IBGE')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('certificado_digital', models.BinaryField(blank=True, help_text='Arquivo .pfx do certificado A1', null=True, verbose_name='certificado digital')),
                ('certificado_senha', models.CharField(blank=True, help_text='Senha criptografada', max_length=255, verbose_name='senha do certificado')),
                ('certificado_validade', models.DateField(blank=True, null=True, verbose_name='validade do certificado')),
                ('nfse_serie_padrao', models.CharField(default='1', max_length=10, verbose_name='série NFS-e padrão')),
                ('nfse_ultimo_rps', models.PositiveIntegerField(default=0, verbose_name='último RPS')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('pode_operar_caixa', models.BooleanField(default=False, verbose_name='pode operar caixa')),
                ('pode_emitir_nfse', models.BooleanField(default=False, verbose_name='pode emitir NFS-e')),
                ('pode_cancelar_nfse', models.BooleanField(default=False, verbose_name='pode cancelar NFS-e')),
                ('pode_aprovar_fechamento', models.BooleanField(default=False, verbose_name='pode aprovar fechamento')),
                ('pode_exportar_dados', models.BooleanField(default=False, verbose_name='pode exportar dados')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.tenant', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('CHEQUE', 'Cheque'), ('OUTROS', 'Outros')], max_length=20, verbose_name='tipo')),
                ('taxa_percentual', models.DecimalField(decimal_places=4, default=0, help_text='Taxa cobrada pela operadora (ex: 0.0199 = 1.99%)', max_digits=5, verbose_name='taxa percentual')),
                ('prazo_recebimento', models.PositiveIntegerField(default=0, help_text='Dias para recebimento após a venda', verbose_name='prazo recebimento (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('conta_contabil', models.CharField(blank=True, help_text='Código da conta para lançamento', max_length=20, verbose_name='conta contábil')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
    ]
