# Generated by Django 6.0.1 on 2026-02-06 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sistema', models.CharField(choices=[('RI', 'Registro de Imóveis'), ('NOTAS', 'Notas'), ('PROTESTO', 'Protesto'), ('RTDPJ', 'RTDPJ'), ('RCPN', 'RCPN')], max_length=20, verbose_name='sistema')),
                ('tipo_conexao', models.CharField(choices=[('FIREBIRD', 'Firebird'), ('MSSQL', 'MsSQL Server'), ('POSTGRES', 'PostgreSQL')], max_length=20, verbose_name='tipo de conexão')),
                ('host', models.CharField(max_length=255, verbose_name='host')),
                ('porta', models.PositiveIntegerField(verbose_name='porta')),
                ('database', models.CharField(help_text='Nome do banco ou caminho do arquivo (Firebird)', max_length=255, verbose_name='banco de dados')),
                ('usuario', models.CharField(max_length=100, verbose_name='usuário')),
                ('senha', models.CharField(max_length=255, verbose_name='senha')),
                ('charset', models.CharField(default='WIN1252', max_length=20, verbose_name='charset')),
                ('instancia', models.CharField(blank=True, help_text='Instância do SQL Server (opcional)', max_length=100, verbose_name='instância')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'conexão externa',
                'verbose_name_plural': 'conexões externas',
                'ordering': ['sistema'],
                'unique_together': {('tenant', 'sistema')},
            },
        ),
    ]
