# Generated by Django 6.0.1 on 2026-02-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rotina_sql_content_extra'),
        ('core', '0002_conexaoexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaoexterna',
            name='sistema_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexoes_externas', to='backoffice.sistema', verbose_name='sistema (novo)'),
        ),
    ]
