# Generated by Django 6.0.1 on 2026-02-06 20:59

from django.db import migrations

def migrate_sistema_data(apps, schema_editor):
    ConexaoExterna = apps.get_model('core', 'ConexaoExterna')
    Sistema = apps.get_model('backoffice', 'Sistema')
    
    # Map old choice values to Sistema names
    # Note: Assuming Sistema records with these exact names exist as confirmed by user
    # Choices were: RI (Registro de Imóveis), NOTAS, PROTESTO, RTDPJ, RCPN
    
    for conexao in ConexaoExterna.objects.all():
        sistema_nome = conexao.sistema
        
        # Simple normalization if needed, or direct lookup
        # If the old value stored was the CHOICE KEY (e.g. "RI"), but Sistema name is "Registro de Imóveis"
        # we might need a mapping.
        # But if user says "same data with same names", I'll try exact match first.
        # If conexao.sistema is "RI", and Sistema name is "Registro de Imóveis", strict match fails.
        # Let's try to be smart: Check exact match first, then map common abbreviations if strict fails.
        
        target_sistema = Sistema.objects.filter(nome__iexact=sistema_nome).first()
        
        if not target_sistema:
            # Fallback for known abbreviations if strict match fails
            if sistema_nome == 'RI':
                target_sistema = Sistema.objects.filter(nome__icontains="Registro de Imóveis").first()
            elif sistema_nome == 'RTDPJ':
                 target_sistema = Sistema.objects.filter(nome__icontains="Títulos e Documentos").first()
        
        if target_sistema:
            conexao.sistema_new = target_sistema
            conexao.save()
        else:
             print(f"Warning: No matching Sistema found for '{sistema_nome}'")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conexaoexterna_sistema_new'),
        ('backoffice', '0001_initial'), # Ensure backoffice is available
    ]

    operations = [
        migrations.RunPython(migrate_sistema_data),
    ]
