# Generated by Django 6.0.1 on 2026-02-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rotina_sql_content_extra'),
        ('core', '0004_auto_20260206_1759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conexaoexterna',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conexaoexterna',
            name='sistema',
        ),
        migrations.RenameField(
            model_name='conexaoexterna',
            old_name='sistema_new',
            new_name='sistema',
        ),
        migrations.AlterUniqueTogether(
            name='conexaoexterna',
            unique_together={('tenant', 'sistema')},
        ),
    ]
