# Generated by Django 6.0.1 on 2026-02-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rotina_sql_content_extra'),
        ('core', '0005_remove_conexaoexterna_sistema_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaoexterna',
            name='rotinas',
            field=models.ManyToManyField(blank=True, related_name='conexoes', to='backoffice.rotina', verbose_name='rotinas disponíveis'),
        ),
        migrations.AlterField(
            model_name='conexaoexterna',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexoes_externas', to='backoffice.sistema', verbose_name='sistema'),
        ),
    ]
