# Generated by Django 5.2.11 on 2026-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conexaoexterna_rotinas_alter_conexaoexterna_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='chave_servico_andamento_ri',
            field=models.CharField(blank=True, default='', help_text='Chave do serviço de andamento para Registro de Imóveis. Substituída automaticamente como @SERVICOANDAMENTO nas rotinas SQL.', max_length=50, verbose_name='chave serviço andamento (RI)'),
        ),
    ]
