# Generated by Django 6.0.1 on 2026-02-12 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_chave_servico_andamento_ri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('PROTOCOLO_VENCENDO', 'Protocolo vencendo'), ('PROTOCOLO_VENCIDO', 'Protocolo vencido'), ('FECHAMENTO_PENDENTE', 'Fechamento pendente'), ('GERAL', 'Geral')], default='GERAL', max_length=30, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('referencia_id', models.CharField(blank=True, help_text='ID do objeto referenciado (ex: protocolo)', max_length=100, verbose_name='referência')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Se nulo, a notificação é para todos do tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
