# Generated by Django 6.0.1 on 2026-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificacao_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cnae_principal',
            field=models.CharField(blank=True, help_text='Código CNAE fiscal principal (7 dígitos)', max_length=7, verbose_name='CNAE principal'),
        ),
    ]
