# Generated by Django 6.0.1 on 2026-02-15 20:38

import caixa_nfse.core.encrypted_fields
from django.db import migrations


def encrypt_existing_passwords(apps, schema_editor):
    """Encrypt all existing plaintext passwords."""
    from caixa_nfse.core.encrypted_fields import _get_fernet, _is_encrypted

    ConexaoExterna = apps.get_model("core", "ConexaoExterna")
    fernet = _get_fernet()

    for conexao in ConexaoExterna.objects.all():
        if conexao.senha and not _is_encrypted(conexao.senha):
            conexao.senha = fernet.encrypt(conexao.senha.encode()).decode()
            conexao.save(update_fields=["senha"])


def decrypt_existing_passwords(apps, schema_editor):
    """Reverse: decrypt all passwords back to plaintext."""
    from caixa_nfse.core.encrypted_fields import _get_fernet, _is_encrypted

    ConexaoExterna = apps.get_model("core", "ConexaoExterna")
    fernet = _get_fernet()

    for conexao in ConexaoExterna.objects.all():
        if conexao.senha and _is_encrypted(conexao.senha):
            conexao.senha = fernet.decrypt(conexao.senha.encode()).decode()
            conexao.save(update_fields=["senha"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_cnae_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexaoexterna',
            name='senha',
            field=caixa_nfse.core.encrypted_fields.EncryptedCharField(max_length=500, verbose_name='senha'),
        ),
        migrations.RunPython(
            encrypt_existing_passwords,
            reverse_code=decrypt_existing_passwords,
        ),
    ]
