# Generated by Django 6.0.1 on 2026-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='sql_content_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo SQL Adicional (Opcional)'),
        ),
    ]
