# Generated by Django 5.2.11 on 2026-02-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rotina_sql_content_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoColunaRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_sql', models.CharField(help_text='Nome exato da coluna retornada pela query SQL', max_length=100, verbose_name='coluna SQL')),
                ('campo_destino', models.CharField(choices=[('protocolo', 'Protocolo'), ('status_item', 'Status'), ('quantidade', 'Quantidade'), ('valor', 'Valor Principal'), ('descricao', 'Descrição'), ('cliente_nome', 'Nome do Apresentante'), ('emolumento', 'Emolumento'), ('taxa_judiciaria', 'Taxa Judiciária'), ('iss', 'ISS'), ('fundesp', 'FUNDESP'), ('funesp', 'FUNESP'), ('estado', 'Estado'), ('fesemps', 'FESEMPS'), ('funemp', 'FUNEMP'), ('funcomp', 'FUNCOMP'), ('fepadsaj', 'FEPADSAJ'), ('funproge', 'FUNPROGE'), ('fundepeg', 'FUNDEPEG'), ('fundaf', 'FUNDAF'), ('femal', 'FEMAL'), ('fecad', 'FECAD')], max_length=50, verbose_name='campo destino')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='backoffice.rotina')),
            ],
            options={
                'verbose_name': 'Mapeamento de Coluna',
                'verbose_name_plural': 'Mapeamentos de Colunas',
                'ordering': ['rotina', 'campo_destino'],
                'unique_together': {('rotina', 'campo_destino')},
            },
        ),
    ]
