# Generated by Django 5.2.11 on 2026-02-04 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tabela', models.CharField(db_index=True, max_length=100, verbose_name='tabela')),
                ('registro_id', models.CharField(db_index=True, max_length=36, verbose_name='ID do registro')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('EXPORT', 'Exportação'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição')], db_index=True, max_length=20, verbose_name='ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID da sessão')),
                ('dados_antes', models.JSONField(blank=True, help_text='Estado do registro antes da alteração', null=True, verbose_name='dados antes')),
                ('dados_depois', models.JSONField(blank=True, help_text='Estado do registro após a alteração', null=True, verbose_name='dados depois')),
                ('campos_alterados', models.JSONField(blank=True, help_text='Lista de campos que foram alterados', null=True, verbose_name='campos alterados')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('hash_registro', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='hash do registro')),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64, verbose_name='hash anterior')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'permissions': [('view_audit_report', 'Can view audit reports'), ('export_audit_log', 'Can export audit logs')],
            },
        ),
    ]
