# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria', to='core.tenant', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['tenant', 'tabela', 'registro_id'], name='auditoria_r_tenant__cc93da_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['tenant', 'usuario', 'created_at'], name='auditoria_r_tenant__1de763_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['created_at'], name='auditoria_r_created_04d3fc_idx'),
        ),
    ]
