# Generated by Django 5.2.11 on 2026-02-04 19:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero_rps', models.PositiveIntegerField(db_index=True, verbose_name='número RPS')),
                ('serie_rps', models.CharField(default='1', max_length=10, verbose_name='série RPS')),
                ('numero_nfse', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='número NFS-e')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=50, verbose_name='código verificação')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='data emissão')),
                ('competencia', models.DateField(help_text='Mês/ano de competência', verbose_name='competência')),
                ('discriminacao', models.TextField(verbose_name='discriminação do serviço')),
                ('valor_servicos', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor dos serviços')),
                ('valor_deducoes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor deduções')),
                ('base_calculo', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='base de cálculo')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor COFINS')),
                ('valor_inss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor INSS')),
                ('valor_ir', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor IR')),
                ('valor_csll', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor CSLL')),
                ('aliquota_iss', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='alíquota ISS')),
                ('valor_iss', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='valor ISS')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS retido')),
                ('valor_liquido', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='valor líquido')),
                ('local_prestacao_ibge', models.CharField(max_length=7, verbose_name='código IBGE local prestação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIANDO', 'Enviando'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('SUBSTITUIDA', 'Substituída')], default='RASCUNHO', max_length=20, verbose_name='status')),
                ('protocolo', models.CharField(blank=True, max_length=100, verbose_name='protocolo')),
                ('xml_rps', models.TextField(blank=True, help_text='XML enviado à prefeitura', verbose_name='XML RPS')),
                ('xml_nfse', models.TextField(blank=True, help_text='XML retornado pela prefeitura', verbose_name='XML NFS-e')),
                ('pdf_url', models.URLField(blank=True, verbose_name='URL PDF')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo cancelamento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='data cancelamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='clientes.cliente', verbose_name='tomador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('nota_substituida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_substituta', to='nfse.notafiscalservico', verbose_name='nota substituída')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'nota fiscal de serviço',
                'verbose_name_plural': 'notas fiscais de serviço',
                'ordering': ['-data_emissao', '-numero_rps'],
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('GERACAO', 'Geração RPS'), ('ENVIO', 'Envio à Prefeitura'), ('AUTORIZACAO', 'Autorização'), ('REJEICAO', 'Rejeição'), ('CONSULTA', 'Consulta'), ('CANCELAMENTO', 'Cancelamento'), ('SUBSTITUICAO', 'Substituição')], max_length=20, verbose_name='tipo')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('protocolo', models.CharField(blank=True, max_length=100, verbose_name='protocolo')),
                ('xml_envio', models.TextField(blank=True, verbose_name='XML envio')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML retorno')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('sucesso', models.BooleanField(default=True, verbose_name='sucesso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_fiscais', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='nfse.notafiscalservico', verbose_name='nota')),
            ],
            options={
                'verbose_name': 'evento fiscal',
                'verbose_name_plural': 'eventos fiscais',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ServicoMunicipal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo_lc116', models.CharField(db_index=True, max_length=10, verbose_name='código LC 116')),
                ('codigo_municipal', models.CharField(blank=True, max_length=20, verbose_name='código municipal')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='alíquota ISS')),
                ('municipio_ibge', models.CharField(db_index=True, max_length=7, verbose_name='código IBGE município')),
            ],
            options={
                'verbose_name': 'serviço municipal',
                'verbose_name_plural': 'serviços municipais',
                'ordering': ['codigo_lc116'],
                'unique_together': {('codigo_lc116', 'municipio_ibge')},
            },
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='nfse.servicomunicipal', verbose_name='serviço'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalservico',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_rps', 'serie_rps'), name='unique_rps'),
        ),
    ]
