# Generated by Django 6.0.1 on 2026-02-12 08:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_chave_servico_andamento_ri'),
        ('nfse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='ambiente',
            field=models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=15, verbose_name='ambiente'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='backend_utilizado',
            field=models.CharField(blank=True, choices=[('mock', 'Mock (Testes)'), ('portal_nacional', 'Portal Nacional'), ('focus_nfe', 'Focus NFe'), ('tecnospeed', 'TecnoSpeed'), ('pynfe', 'PyNFe Híbrido')], max_length=20, verbose_name='backend utilizado'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='chave_acesso',
            field=models.CharField(blank=True, help_text='Chave de acesso da NFS-e Nacional (50 dígitos)', max_length=50, verbose_name='chave de acesso'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='id_dps',
            field=models.CharField(blank=True, help_text='Identificador da DPS no Portal Nacional', max_length=100, verbose_name='ID DPS'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_cbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Contribuição sobre Bens e Serviços', max_digits=14, verbose_name='valor CBS'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_ibs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Imposto sobre Bens e Serviços', max_digits=14, verbose_name='valor IBS'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoNFSe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('backend', models.CharField(choices=[('mock', 'Mock (Testes)'), ('portal_nacional', 'Portal Nacional'), ('focus_nfe', 'Focus NFe'), ('tecnospeed', 'TecnoSpeed'), ('pynfe', 'PyNFe Híbrido')], default='mock', max_length=20, verbose_name='provedor de emissão')),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=15, verbose_name='ambiente')),
                ('gerar_nfse_ao_confirmar', models.BooleanField(default=False, help_text='Se ativo, gera NFS-e automaticamente ao confirmar movimento', verbose_name='gerar NFS-e ao confirmar pagamento')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='API token')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API secret')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_nfse', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'configuração NFS-e',
                'verbose_name_plural': 'configurações NFS-e',
            },
        ),
    ]
