# Generated by Django 5.2.11 on 2026-02-12 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_chave_servico_andamento_ri'),
        ('nfse', '0002_nfse_nacional_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('backend', models.CharField(db_index=True, max_length=20, verbose_name='backend')),
                ('metodo', models.CharField(max_length=10, verbose_name='método HTTP')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('headers_envio', models.JSONField(default=dict, help_text='Headers sanitizados — sem tokens ou senhas', verbose_name='headers enviados')),
                ('body_envio', models.TextField(blank=True, verbose_name='body enviado')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='status code')),
                ('headers_retorno', models.JSONField(blank=True, null=True, verbose_name='headers recebidos')),
                ('body_retorno', models.TextField(blank=True, verbose_name='body recebido')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('duracao_ms', models.IntegerField(blank=True, null=True, verbose_name='duração (ms)')),
                ('sucesso', models.BooleanField(default=False, verbose_name='sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='request ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='nfse.notafiscalservico', verbose_name='nota fiscal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'log de API NFS-e',
                'verbose_name_plural': 'logs de API NFS-e',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['tenant', 'data_hora'], name='nfse_nfseap_tenant__e00b6e_idx'), models.Index(fields=['nota'], name='nfse_nfseap_nota_id_38dba4_idx'), models.Index(fields=['backend', 'data_hora'], name='nfse_nfseap_backend_695be9_idx')],
            },
        ),
    ]
