# Generated by Django 5.2.11 on 2026-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0003_add_nfse_api_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonfse',
            name='webhook_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token para autenticação de callbacks dos gateways', max_length=64, verbose_name='token do webhook'),
        ),
    ]
