# Generated by Django 6.0.1 on 2026-02-15 21:52

import caixa_nfse.core.encrypted_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0004_add_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='json_retorno_gateway',
            field=models.JSONField(blank=True, help_text='Resposta JSON/dict bruta do gateway para auditoria', null=True, verbose_name='retorno do gateway'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='mensagem_erro',
            field=models.TextField(blank=True, help_text='Última mensagem de erro/rejeição para consulta rápida', verbose_name='mensagem de erro'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='uuid_transacao',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Chave de idempotência para evitar duplicidade em retries', verbose_name='UUID transação'),
        ),
        migrations.AlterField(
            model_name='configuracaonfse',
            name='api_secret',
            field=caixa_nfse.core.encrypted_fields.EncryptedCharField(blank=True, max_length=500, verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='configuracaonfse',
            name='api_token',
            field=caixa_nfse.core.encrypted_fields.EncryptedCharField(blank=True, max_length=500, verbose_name='API token'),
        ),
    ]
